### ISSUE TITLE
Machine locks up with cartridge inserted

### ISSUE THREAD

**Issue by deftmega** [MEGA65/mega65-core#202] opened 2020-04-09 00:57 UTC
Encounterd in 156/65: Machine won't boot if cartridge is inserted. Also not possible to run flash or any other menu. Blue screen with interesting white block visible.

**Comment by deftmega** [comment] 2020-10-12 06:03
This is still the case for easyflash. Behavior changes on each reset (reproducible) until menu appears. Can't start any title tho. Other cartridges e.g. Sam's Journey work.

**Comment by deftmega** [comment] 2022-01-03 15:56
easyflash 2 is no longer working. this is still the case. Sam's Journey and super breadbox work. We will look into this later.

**Comment by lydon42** [comment] 2022-05-29 16:25
this is a #564

**Comment by lydon42** [comment] 2023-04-10 18:01
Ultimax boot works with [3fcf2de](https://github.com/MEGA65/mega65-core/commit/3fcf2deceaada30f1a8e1b219eb943e737211d65)
This is a duplicate of #684

**Closed by lydon42** 2023-04-10 18:01 UTC
Labels: enhancement
