### ISSUE TITLE
In the Freezer when choosing new D81 or D65 Image - System Hangs

### ISSUE THREAD

**Issue by oe3gwu** [MEGA65/mega65-core#570] opened 2022-06-07 10:35 UTC
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: (MEGA65)
 - Core Commit: (187-899CF4F)
 - ROM Release: (920365)

**Describe the bug**
When I enter the FREEZER (0.1.4) and want to create a new D81 or D65 Image, the System hangs. Border color changes sometimes to red or black.

**To Reproduce**
1. Go to the FREEZER
2. Click on 0
3. Choose new D65 HD Image
4. System hang.

**Expected behavior**
A new Image or a Dialog with a Filename.

**Screenshots**
![IMG_0674](https://user-images.githubusercontent.com/17622063/172359590-10da0865-6a53-401b-8db9-67cf9a307a17.jpeg)

![IMG_0675](https://user-images.githubusercontent.com/17622063/172359607-343a646b-187c-4eae-8e50-fa1fa44ab20c.jpeg)

**Comment by dansanderson** [comment] 2022-06-07 17:21
I'm also having an issue with D81 disk image creation, but I make it to the name prompt and the "Creating..." message with the flashing border. It flashes like it's doing something but never finishes. Note that this appears to be a regression in newer firmware/FREEZER.M65 because I was able to do it "before," but I haven't tried looking for the version that broke it yet.

Should we track these as separate issues?

**Comment by gurcei** [comment] 2022-06-08 23:57
Had another debug session just now on my devkit, some further notes here:
- https://discord.com/channels/719326990221574164/984239895918837791/984239899446222878

On this occasion, I noticed the system tried to load the `MAKEDISK.M65` file from the sd-card but failed.

When I took a look at my sd-card, it indeed was missing.

After adding the `MAKEDISK.M65` file onto the sd-card and trying again, I finally got the popup window offering me to type the filename:
![image](https://user-images.githubusercontent.com/20013309/172736422-1d91a97b-4a88-4300-ba27-3ad59a715305.png)

So I'm wondering if it's possible that this file went missing on your sd-cards too perhaps?

As for why it might have happened, not sure. I thought perhaps some of you may have prepared your own sd-cards anew via the mega65 config menu's fdisk utility, and I wondered if it perhaps failed to extract out this `MAKEDISK.M65` file from the core? I noticed that in a screenshot from a past user, that the file was in there:
![image](https://user-images.githubusercontent.com/20013309/172736627-b689bf83-6399-4fe8-a447-4b3a68431695.png)

...but who knows, perhaps something went amiss with this pre-populating process in more recent cores?

**Comment by gurcei** [comment] 2022-06-09 10:29
I still had probs after adding MAKEDISK.M65. Upon debugging them, seemed like there was a bug when traversing dir-entry clusters. I provided more details and a new `MAKEDISK.M65` file that affected users can try on their sd-cards. Let me know if this resolves your situation or not:

https://discord.com/channels/719326990221574164/984239895918837791/984400989614407720

**Comment by oe3gwu** [comment] 2022-06-09 10:44
Thank you!

I will try this later today. Keep you posted here.

**Comment by gurcei** [comment] 2022-06-12 05:41
Ok, digging into this issue revealed another edge-case issue (if the last direntry of a directory is on the end of a cluster). This edge-case impacted both the hypervisor and makedisk, so I've added fixes to both and will roll them into my upcoming PR.

**Comment by gurcei** [comment] 2022-06-13 06:41
Ok, judging from the feedback from several affected users, feel like the fix for this is sorted now, the PR is still underway, but will close now.

**Closed by gurcei** 2022-06-13 06:41 UTC
Labels: new
