### ISSUE TITLE
SD cards MBR is getting overwritten so often

### ISSUE THREAD

**Issue by adtbm** [MEGA65/mega65-core#253] opened 2020-07-13 01:18 UTC
it happens quite often, that the MBR is getting killed on the SD card.

Pauls quote: 
"writing over sector 0 is also the most likely brain fade to happen with random access to the SD card.
I should make it so that there is a special sequence required to write the MBR since it is so important."

**Comment by Ben-401** [comment] 2020-07-13 02:57
by killed do you mean overwritten? with zeros or garbage? just one byte or many?
and on what branch exactly, as I dont have a "138-hd-5503" branch as reported in issue #252.

**Comment by gardners** [comment] 2020-07-13 05:05
What Anton is talking about implementing here is a safety catch, so that you can't easily cause the MBR to be overwritten.  The problem is branch independent: Basically if you write $03 to $D680, when no sector number has been supplied, then it will write over the MBR, e.g., if some program writes over the IO space without really paying attention.  This is also why in the longer term direct SD card access will be disabled.

**Comment by Ben-401** [comment] 2020-08-20 05:55
bump - just testing the "https://github.com/MEGA65/mega65-test-procedures"

**Comment by Ben-401** [comment] 2020-08-20 07:11
bump

**Comment by lydon42** [comment] 2022-10-02 10:54
Is this still a problem?

**Comment by lydon42** [comment] 2024-08-17 14:40
Possible related to (and perhaps also fixed by) #264 ?

**Comment by gardners** [comment] 2024-08-17 16:33
Yes, fixed by #264. Evidence for this is that noone has complained for several years about this happening,

**Closed by gardners** 2024-08-17 16:33 UTC
Labels: clarification required, cleanup-fixed
