### ISSUE TITLE
issue 115 nexys4ddr-widget-20191105.02-HEAD_n-13bf229+DIRTY.bit freeze menu not working

### ISSUE THREAD

**Issue by adtbm** [MEGA65/mega65-core#128] opened 2019-11-08 22:52 UTC
nexys4ddr-widget-20191105.02-HEAD_n-13bf229+DIRTY.bit

Freezemenu crashes on leaving
regardless if in C65 or c64 mode

**Comment by adtbm** [comment] 2019-11-08 23:07
same issue on stable bitstream:
nexys4ddr-widget-20191103.15-HEAD_n-4034f19+DIRTY.bit

**Comment by gardners** [comment] 2019-11-13 08:55
This seems to be randomly fixed by #116. That this should work is totally unexplained.  It would still be good to discover the root cause.

**Closed** 2021-02-09 02:43 UTC
Labels: bug
