### ISSUE TITLE
Freezer erroneously activates vertical crosshair line

### ISSUE THREAD

**Issue by steph72** [MEGA65/mega65-core#400] opened 2021-06-14 15:24 UTC
Sometimes, after accessing the freezer and returning, a vertical red line is overlaid on the screen (and stays there until reset).

![image0](https://user-images.githubusercontent.com/51749597/121917327-4afd3100-cd35-11eb-9ed1-ef6add842326.jpg)

**Comment by gardners** [comment] 2021-06-15 07:27
I think I know the cause for this: Those registers read different values to what can be written to them.
They should be made to read the written values if read from hypervisor mode.

**Comment by gurcei** [comment] 2021-07-01 23:25
I tried a recent bitstream, and it seemed to be this problem has gone away. Ok to close the ticket?

**Comment by gardners** [comment] 2021-07-02 08:31
Yes, I believe I fixed it, so close the issue.

**Closed** 2021-07-03 09:02 UTC
Labels: bug
