### ISSUE TITLE
White screen when going into BIOS

### ISSUE THREAD

**Issue by adtbm** [MEGA65/mega65-core#144] opened 2019-11-25 17:36 UTC
This Bug only happens after powering ON. but it happens every time !
- hold ALT untill hypervisor submenu appears (To press 1 for utilities or 2 for SD tools)

now pressing 1 or pressing 2 will result in White screen....

pressing RESET button on R2 board and pressing ALT again works as work around.

**Comment by gardners** [comment] 2019-11-26 01:03
Please test with latest unstable bitstream, as I can't reproduce it here on N4DDR-widget board with head of unstable branch

**Comment by gardners** [comment] 2020-02-25 10:49
Do you still see this on the latest stable_base?

**Comment by deftmega** [comment] 2020-03-20 11:28
yes! Also entering FDISK is affected!
Happens on every Cold boot if you directly try to go to either FDISK or BIOS MENU!

**Comment by gardners** [comment] 2020-03-24 18:15
Problem is an interrupt of some kind triggering before the utility can mask them, combined with there being no valid ROM ready (even OpenROM requires the ROM vectors at $0300+ to be initialised)

**Comment by gardners** [comment] 2020-03-25 00:00
Fixed. Ready for merging in.

**Comment by frehwagen** [comment] 2020-04-09 18:48
Merged to stable_base/14.

**Closed by frehwagen** 2020-04-09 18:48 UTC
Labels: bug
