### ISSUE TITLE
Allow DMA src/dst addresses to cross MB boundaries

### ISSUE THREAD

**Issue by ki-bo** [MEGA65/mega65-core#826] opened 2024-08-29 19:04 UTC
Tested with 0.96 release core

A DMA job filling or copying data does not update its configured MB part of the src/dst address during job execution. For example, if a copy job crosses a MB boundary for its src address from $81fffff to $8200000 it will actually jump back to $8100000.

**Comment by lgblgblgb** [comment] 2024-08-30 06:18
I'm wondering if this is really a bug? I remember when I wrote the emulation of this, and @gardners said (after I had question on this very topic), this is the desired behaviour to be wrapped within the 1Mbyte region, ie DMA cannot cross 1 Mbyte boundary by design. Well, "IIRC" ... In fact, I have some faint memories that C65 may do this "cannot cross" policy on 64K boundary but it was fixed to be at 1MByte basis with the mega65-core.

https://github.com/lgblgblgb/xemu/commit/8e9fb8658cff02086b1cbafb8ce1e6b8e86c5a2c

    // On C65, DMA cannot cross 64K boundaries, so the right mask is 0xFFFF
    // On MEGA65 it seems to be 1Mbyte, thus the mask should be 0xFFFFF
    // No idea about the list mask, which is not the normal dma read/write ops,
    // but reading the DMA listself only.

**Comment by lydon42** [comment] 2024-08-30 09:03
Good point @lgblgblgb 
@gardners also mentioned that this is a protection so that a DMA job does not cross from  $FExxxxx to $FFxxxxx.
So perhaps we should keep this as it is, as protecting against this overflow is a rather special check and would effect other address ranges, like $BExxxxx to $BFxxxxx (end of 64MB Attic RAM) or $8Exxxxx to $8Fxxxxx (end of 16MB Cellar RAM).

**Comment by lgblgblgb** [comment] 2024-08-30 11:36
Also there can be corner cases when something other depends on it, ie, doing a DMA job at the end of an 1Mbyte "slice" (right at the end) with chained jobs, so if MB is updated the next DMA "sub-job" in the chain will experience different MB setting which was not the case before.

So my point: one thing is the unwanted effect to really cross MB boundary (@lydon42) the other is the side effect to have MB modified (without an exact enhanced DMA option for this) within a chained job which was forbidden before.

With all my respect @ki-bo I would vote against this change. However it must be made clear (if it's not that way already) in documents (maybe even in VHDL as comment) etc, that non-cross-MB policy is intentional and the desired behaviour.

**Comment by ki-bo** [comment] 2024-08-30 12:56
After discussion with @gardners we propose to add another DMA option to disable the 1MB limit for the current job.
- This will not introduce backwards compatibility issues with existing code
- That option will be ignored in HYPPO context to not impact security

**Comment by lydon42** [comment] 2024-09-04 08:02
Moving this to near future, is it no release requirement.
Steering Group has approved the implementation as a DMA option.

**Comment by lydon42** [comment] 2024-09-09 11:14
Steering Group decided to include the global option bit (4 votes for global bit plus job option, 2 votes for job option only, 2 abstains).

So please also implement the global option bit in $D703.

**Closed as completed** 2024-09-14 01:56 UTC
Labels: enhancement, SGA
