### ISSUE TITLE
compulation error while running make 

### ISSUE THREAD

**Issue by DianaBarber8880** [MEGA65/mega65-core#231] opened 2020-06-10 00:35 UTC
![image](https://user-images.githubusercontent.com/37940492/84213877-f6f7b500-ab00-11ea-88b2-133ff5b0bcaf.png)
followed the directions in the file docs/build.md 
this error appears when I run the makefile with the make command

**Comment by gardners** [comment] 2020-06-10 06:59
The dead process MIGHT be because you don't have enough RAM -- expect Vivado to potentially peak above 8GB of RAM usage.  Similarly lack of disk space might cause trouble.  What's the spec of you system?

But excited to see other folks trying to build bitstreams!

**Comment by gardners** [comment] 2020-06-10 23:35
Yes, almost certainly the 4GB VM RAM is a problem.  What is your native OS? Vivado runs natively on Windows, for example, if you prefer to avoid the VM.

**Comment by Ben-401** [comment] 2020-06-24 11:25
my vm is allocated 8G and within the VM I can do the following:
- I can generate the bitstream using the Makefile,
- but when If loading the Vivado GUI, followed by Opening Implemented Design, the VM disappears from my Host- ie crashes.

Were you successful in building the design by allocating more RAM to the VM?

**Comment by lydon42** [comment] 2021-12-20 18:20
Not a bug, more something that should be handled on discord.
Also over an year old.
Closing.

**Closed by lydon42** 2021-12-20 18:20 UTC
